blog/urls.py
from django.urls import path

from .feeds import LatestPostFeed, AtomSiteNewsFeed

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='home'),
    path('<slug:slug>/', views.post_detail, name='post_detail'),
    path('comment-reply/', views.reply_page, name='comment_reply'),
    path('category/<slug:slug>', views.posts_by_category, name='posts_by_category'),
    path('tag/<slug:slug>', views.posts_by_tag, name='posts_by_tag'),
    path('feed/rss', LatestPostFeed(), name='post_feed'),
    path('feed/atom', AtomSiteNewsFeed()),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
import debug_toolbar

sitemaps = {
    'posts': PostSitemap
}

urlpatterns = [
    path('shop/', include('shop.urls'), name='shop-urls'),
    path('accounts/', include('account.urls'), name='account-urls'),
    path('polls/', include('polls.urls'), name='polls-urls'),
    path('blog/', include('blog.urls'), name='blog-urls'),
    path('summernote/', include('django_summernote.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
    path('cms/admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone

from django.conf import settings


# Creating model manager
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status=1)


class Category(models.Model):
    name = models.CharField(max_length=200, unique=True)
    slug = models.CharField(max_length=200, unique=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='blog_categories')
    updated_on = models.DateTimeField(auto_now=True)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=200, unique=True)
    slug = models.CharField(max_length=200, unique=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='blog_tags')
    updated_on = models.DateTimeField(auto_now=True)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    STATUS = (
        (0, "Draft"),
        (1, "Publish")
    )

    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='blog_posts')
    updated_on = models.DateTimeField(auto_now=True)
    created_on = models.DateTimeField(auto_now_add=True)
    published_on = models.DateTimeField(default=timezone.now)
    content = models.TextField()
    status = models.IntegerField(choices=STATUS, default=0)
    image = models.ImageField(upload_to='images/featured/%Y/%m/%d/')
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        related_name='blog_posts_categories',
        null=True,
        blank=True
    )
    tags = models.ManyToManyField(Tag)

    class Meta:
        ordering = ['-published_on']

    objects = models.Manager()  # The default manager
    published = PublishedManager()  # Our custom manager

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        from django.urls import reverse

        return reverse('blog:post_detail', kwargs={'slug': str(self.slug)})


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    parent = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)

blog/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count

from .models import Post, Category, Tag, Comment
from .forms import CommentForm


def post_list(request):
    posts = Post.published.all()
    template_name = 'blog/index.html'

    paginator = Paginator(posts, 3)  # 3 posts in each page
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range, deliver last page of results
        posts = paginator.page(paginator.num_pages)

    return render(request, template_name, {
        'posts': posts,
        page: 'pages'
    })


def post_detail(request, slug):
    template_name = 'blog/post_detail.html'
    post = get_object_or_404(Post, slug=slug, status=1)
    comments = post.comments.filter(active=True).order_by('-created_on')
    new_comment = None
    # Comment posted
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-published_on')[:6]

    return render(request, template_name, {
        'post': post,
        'comments': comments,
        'new_comment': new_comment,
        'comment_form': comment_form,
        'similar_posts': similar_posts
    })


def reply_page(request):
    if request.method == 'POST':

        form = CommentForm(request.POST)

        if form.is_valid():
            post_id = request.POST.get('post_id')
            parent_id = request.POST.get('parent')
            post_url = request.POST.get('post_url')

            reply = form.save(commit=False)

            reply.post = Post(id=post_id)
            reply.parent = Comment(id=parent_id)
            reply.save()

            return redirect(post_url)
        return redirect('/')


def posts_by_category(request, slug):
    template_name = 'blog/post_by_category.html'
    category = get_object_or_404(Category, slug=slug)
    posts = Post.objects.filter(category__slug=slug)

    return render(request, template_name, {
        'posts': posts,
        'category': category
    })


def posts_by_tag(request, slug):
    template_name = 'blog/post_by_tag.html'
    tag = get_object_or_404(Tag, slug=slug)
    posts = Post.objects.filter(tags__name=tag)

    return render(request, template_name, {
        'posts': posts,
        'tag': tag
    })

blog/templates/blog/about.html
{% extends "base.html" %}

{% block content %}


{% endblock %}

blog/templates/blog/comment.html
{% load crispy_forms_tags %}
<div class="border-0 border-start border-2 ps-2" id="{{ comment.id }}">

    <div class="mt-3">
        <strong>{{ comment.name }}</strong>
        {% if  comment.parent.name %} to <strong>{{ comment.parent.name }}</strong>{% endif %}
        <small class="text-muted">On {{ comment.created.date }}</small>
    </div>
    <div class="border p-2 rounded">
        <p>{{ comment.body }}</p>
        <button class="btn btn-primary btn-sm" onclick="handleReply({{ comment.id }})">Reply</button>

        <div id="reply-form-container-{{ comment.id }}" style="display:none">

            <form method="post" action="{% url 'blog:comment_reply' %}" class="mt-3">
                {% csrf_token %}
                <input type="hidden" name="post_id" value="{{ post.id }}">
                <input type="hidden" name="parent" value="{{ comment.id }}">
                <input type="hidden" name="post_url" value="{{ post.get_absolute_url }}">


                {{ comment_form | crispy }}

                <div>
                    <button type="button" onclick="handleCancel({{ comment.id }})" class="btn btn-light border btn-sm">
                        Cancel
                    </button>
                    <button type="submit" class="btn btn-primary btn-sm">Submit</button>
                </div>
            </form>
        </div>
    </div>
    {% for comment in comment.get_comments %}
        {% include 'blog/comment.html' with comment=comment %}
    {% endfor %}
</div>

blog/templates/blog/index.html
{% extends "base.html" %} {% load humanize %}

{% block content %}

    <header class="masthead">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class=" col-md-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h3 class=" site-heading my-4 mt-3 text-white"> Welcome to my awesome Blog </h3>
                        <p class="text-light">We Love Django As much as you do..! &nbsp
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <div class="container">
        <div class="row">

            <!-- Blog Entries Column -->
            <div class="col-md-8 mt-3 left">
                {% for post in posts %}
                    <!-- Blog Post -->
                    <div class="card mb-3">
                        <div class="card-body">
                            <div class="row g-0">
                                <div class="col-md-5">
                                    <div class="ration ratio-16x9">
                                        <img src="{{ post.image.url }}" class="rounded"
                                             width="250" height="250"
                                             alt="{{ post.title }}"/>
                                    </div>
                                </div>
                                <div class="col-md-7 ps-md-3 pt-3 pt-md-0 flex-column">


                                    <h2 class="card-title">{{ post.title }}</h2>
                                    <p class="card-text text-muted h6">
                                       {{ post.created_on|naturaltime }} | published by <a href="#">{{ post.author }}</a> in
                                         <a
                                        href="{% url 'blog:posts_by_category' post.category.slug %}">{{ post.category }}</a> |
                                        <a href="{% url 'blog:post_detail' post.slug %}">{{ post.comments.count }}
                                            comments</a>
                                    </p>

                                    <p class="card-text">{{ post.content|safe|striptags|slice:":200" }}</p>
                                    <a href="{% url 'blog:post_detail' post.slug %}" class="btn btn-primary">Read More
                                        &rarr;</a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% empty %}
                    <h1>OOps..! Noting Found</h1>
                {% endfor %}
            </div>

            {% block sidebar %}
                {% include 'blog/sidebar.html' %}
            {% endblock sidebar %}
            {% include 'blog/pagination.html' with page=posts %}
        </div>
    </div>
{% endblock %}

blog/templates/blog/pagination.html
{% if page.has_other_pages %}
  <ul class="pagination mt-3 mb-0">
    {% if page.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{ page.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled page-item"><span class="page-link">&laquo;</span></li>
    {% endif %}
    {% for i in page.paginator.page_range %}
      {% if page.number == i %}
        <li class="active page-item"><span class="page-link">{{ i }}</span></li>
      {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ page.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled page-item"><span class="page-link">&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}

blog/templates/blog/post_by_category.html
{% extends "base.html" %} {% load humanize %}

{% block content %}

    <header class="masthead">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class=" col-md-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h3 class=" site-heading my-4 mt-3 text-white"> Welcome to my awesome Blog </h3>
                        <p class="text-light">We Love Django As much as you do..! &nbsp
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <div class="container">
        <div class="row">

            <!-- Blog Entries Column -->
            <div class="col-md-8 mt-3 left">
                {% for post in posts %}
                    <!-- Blog Post -->
                    <div class="card mb-4">
                        <div class="card-body">
                            <h2 class="card-title">{{ post.title }}</h2>
                            <a class="card-text text-muted h6">
                                by <a href="#">{{ post.author }}</a> |
                                {{ post.created_on|naturaltime }} |
                                <a href="{% url 'blog:post_detail' post.slug %}">{{ post.comments.count }}
                                    comments</a>
                            </p>

                            <p class="card-text">{{ post.content|safe|striptags|slice:":200" }}</p>
                            <a href="{% url 'blog:post_detail' post.slug %}" class="btn btn-primary">Read More &rarr;</a>
                            <br/>
                            Category: <a href="#">{{ post.category }}</a>
                            <br/>
                            Tags:
                            {% for tag in post.tags.all %}
                                <a href="#">{{ tag.name }}</a>
                            {% empty %}
                                none
                            {% endfor %}
                        </div>

                    </div>

                {% empty %}
                    <h1>OOps..! Noting Found</h1>
                {% endfor %}

            </div>

            {% block sidebar %}
                {% include 'blog/sidebar.html' %}
            {% endblock sidebar %}
            {% include 'blog/pagination.html' with page=posts %}
        </div>
    </div>
{% endblock %}

blog/templates/blog/post_by_tag.html
{% extends "base.html" %} {% load humanize %}

{% block content %}

    <header class="masthead">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class=" col-md-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h3 class=" site-heading my-4 mt-3 text-white"> Welcome to my awesome Blog </h3>
                        <p class="text-light">We Love Django As much as you do..! &nbsp
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <div class="container">
        <div class="row">

            <!-- Blog Entries Column -->
            <div class="col-md-8 mt-3 left">
                {% for post in posts %}
                    <!-- Blog Post -->
                    <div class="card mb-4">
                        <div class="card-body">
                            <h2 class="card-title">{{ post.title }}</h2>
                            <a class="card-text text-muted h6">
                                by <a href="#">{{ post.author }}</a> |
                                {{ post.created_on|naturaltime }} |
                                <a href="{% url 'post_detail' post.slug %}">{{ post.comments.count }}
                                    comments</a>
                            </p>

                            <p class="card-text">{{ post.content|safe|striptags|slice:":200" }}</p>
                            <a href="{% url 'blog:post_detail' post.slug %}" class="btn btn-primary">Read More &rarr;</a>
                            <br/>
                            Category: <a href="#">{{ post.category }}</a>
                            <br/>
                            Tags:
                            {% for tag in post.tags.all %}
                                <a href="#">{{ tag.name }}</a>
                            {% empty %}
                                none
                            {% endfor %}
                        </div>

                    </div>

                {% empty %}
                    <h1>OOps..! Noting Found</h1>
                {% endfor %}

            </div>

            {% block sidebar %}
                {% include 'blog/sidebar.html' %}
            {% endblock sidebar %}
            {% include 'blog/pagination.html' with page=posts %}
        </div>
    </div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% block content %}
    {% load humanize %}
    {% load crispy_forms_tags %}

    <div class="container">
        <div class="row">
            <div class="col-md-8 card mb-4  mt-3 left  top">
                <div class="card-body">
                    <figure>
                        <img src="https://via.placeholder.com/700x400" class="rounded" alt="{{ post.title }}">
                    </figure>
                    <h1> {% block title %} {{ post.title }} {% endblock title %}</h1>

                    <p class=" text-muted">
                        {{ post.created_on|naturaltime }} by
                        <a href="#">{{ post.author }}</a> in
                        <a href="#">{{ post.category }}</a>
                    </p>

                    <p class="card-text ">{{ post.content | safe }}</p>
                    Tags:
                    {% for tag in post.tags.all %}
                        <a href="#">{{ tag.name }}</a>
                    {% empty %}
                        none
                    {% endfor %}
                </div>
                <div class="my-3">
                    <h3>Similar Posts</h3>
                </div>
                <div class="row">
                    {% for post in similar_posts %}
                        <div class="col-md-6 col-sm-6 col-lg-4 mb-3">
                            <div class="card border-0">
                                <div class="ratio ratio-16x9">
                                    <img src="{{ post.image.url }}" class="rounded featured-image-list"
                                         alt="{{ post.title }}" width="200" height="150">
                                </div>
                                <div class="card-body p-0 m-0 mt-2">
                                    <h2 class="card-title h6 my-0 py-0">
                                        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                                    </h2>
                                    <p class="card-text">
                                        <small class="text-muted">
                        <span>{{ post.publish.date }} by
                            <b>{{ post.author }}</b></span>

                                            <!-- <a href="" class="badge badge-light text-muted">{{post.tags.all|join:" "}}</a> -->


                                        </small>
                                    </p>
                                    <!-- <p>{{post.body|truncatechars:100|linebreaks}}</p> -->
                                </div>
                            </div>
                        </div>
                    {% empty %}
                        <p class="text-muted">There is no similar post yet</p>
                    {% endfor %}
                </div>
                <div class="col-md-8 card mb-4 mt-3">
                    <div class="card-body">
                        <!-- comments -->
                        {% with comments.count as total_comments %}
                            <h2>{{ total_comments }} comment{{ total_comments|pluralize }}</h2>
                        {% endwith %}

                        {% if not comments.all %}
                            No comments yet
                        {% else %}
                            {% for comment in comments %}
                                {{ comment.name }}
                                {% include 'blog/comment.html' with comment=comment %}
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
                <div class="col-md-8 card mb-4  mt-3 ">
                    <div class="card-body">
                        {% if new_comment %}
                            <div class="alert alert-success" role="alert">
                                Your comment is awaiting moderation
                            </div>
                        {% else %}
                            <h3>Leave a comment</h3>
                            <form method="post" style="margin-top: 1.3em;">
                                {{ comment_form | crispy }}
                                {% csrf_token %}
                                <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
                            </form>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% block sidebar %} {% include 'blog/sidebar.html' %} {% endblock sidebar %}
        </div>
    </div>
{% endblock content %}

blog/templates/blog/sidebar.html
{% load static%}

{% block sidebar %}

<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right ">
<div class="card my-4">
        <h5 class="card-header">About Us</h5>
    <div class="card-body">
        <p class="card-text"> This awesome blog is made on the top of our Favourite full stack Framework 'Django', follow up the tutorial to learn how we made it..!</p>
        <a href="#"
           class="btn btn-danger">Know more!</a>
    </div>
</div>
</div>





{% endblock sidebar %}