account/urls.py
from django.urls import path

from . import views

app_name = 'account'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('activate/', views.ActivateView.as_view(), name='activate'),
    path('register/', views.RegisterView.as_view(), name='register'),
]

blog/urls.py
from django.urls import path

from .feeds import LatestPostFeed, AtomSiteNewsFeed

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='home'),
    path('<slug:slug>/', views.post_detail, name='post_detail'),
    path('comment-reply/', views.reply_page, name='comment_reply'),
    path('category/<slug:slug>', views.posts_by_category, name='posts_by_category'),
    path('tag/<slug:slug>', views.posts_by_tag, name='posts_by_tag'),
    path('feed/rss', LatestPostFeed(), name='post_feed'),
    path('feed/atom', AtomSiteNewsFeed()),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
import debug_toolbar

sitemaps = {
    'posts': PostSitemap
}

urlpatterns = [
    path('shop/', include('shop.urls'), name='shop-urls'),
    path('accounts/', include('account.urls'), name='account-urls'),
    path('polls/', include('polls.urls'), name='polls-urls'),
    path('blog/', include('blog.urls'), name='blog-urls'),
    path('summernote/', include('django_summernote.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
    path('cms/admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    # /shop/
    path('', views.home, name='home'),
    path('store/', views.store, name='store'),
    path('<slug:category_slug>/', views.store, name='products_by_category'),
    path('<slug:category_slug>/<slug:product_slug>/', views.product_detail, name='product_detail'),

]

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    category_name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    description = models.TextField(max_length=255, blank=True)
    cat_image = models.ImageField(upload_to='photos/categories', blank=True)

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('shop:products_by_category', args=[self.slug])

    def __str__(self):
        return self.category_name


class Product(models.Model):
    product_name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=255, unique=True)
    description = models.TextField(max_length=500, blank=True)
    price = models.IntegerField()
    images = models.ImageField(upload_to='photos/products', blank=True)
    stock = models.IntegerField()
    is_available = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product_name

    def get_url(self):
        return reverse('shop:product_detail', args=[self.category.slug, self.slug])

shop/views.py
from django.shortcuts import render, get_object_or_404

from .models import Product, Category


def home(request):
    products = Product.objects.all().filter(is_available=True)

    context = {
        'products': products,
    }
    return render(request, 'shop/home.html', context)


def store(request, category_slug=None):
    categories = None
    products = None

    if category_slug is not None:
        categories = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=categories, is_available=True)
        product_count = products.count()
    else:
        products = Product.objects.all().filter(is_available=True)
        product_count = products.count()

    context = {
        'products': products,
        'product_count': product_count
    }
    return render(request, 'shop/store.html', context)


def product_detail(request, category_slug, product_slug):
    try:
        single_product = Product.objects.get(category__slug=category_slug, slug=product_slug)
    except Exception as e:
        raise e
    context = {
        'single_product': single_product
    }
    return render(request, 'shop/product_detail.html', context)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Food Blog</title>

    <link
            href="https://fonts.googleapis.com/css?family=Roboto:400,700"
            rel="stylesheet">
    <meta name="google" content="notranslate"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link
            rel="stylesheet"
            href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
            integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
            crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <script type="application/javascript" src="{% static 'js/main.js' %}"></script>

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'blog:home' %}">Food Blog</a>
        <button
                class="navbar-toggler navbar-toggler-right"
                type="button"
                data-toggle="collapse"
                data-target="#navbarResponsive"
                aria-controls="navbarResponsive"
                aria-expanded="false"
                aria-label="Toggle navigation"
        >
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">

                <li class="nav-item text-black">
                    <a
                            class="nav-link text-black font-weight-bold"
                            href="#"
                    >
                        Hi, {{ user.first_name|default:'Guest'|title }}!
                    </a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item text-black">
                        <a class="nav-link text-black font-weight-bold"
                           href="#">Profile</a>
                    </li>
                    <li class="nav-item text-black">
                        <a class="nav-link text-black font-weight-bold"
                           href="{% url 'account:logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item text-black">
                        <a
                                class="nav-link text-black font-weight-bold"
                                href="{% url 'account:login' %}"
                        >Login</a
                        >
                    </li>
                    <li class="nav-item text-black">
                        <a
                                class="nav-link text-black font-weight-bold"
                                href="{% url 'account:register' %}"
                        >Register</a
                        >
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>


{% block content %}
    <!-- Content Goes here -->
{% endblock content %}

<!-- Footer -->
<footer class="py-3 bg-grey">
    <p class="m-0 text-dark text-center ">Copyright &copy; Food Blog</p>
</footer>

</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block content %}

    <header class="masthead">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class=" col-md-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h3 class=" site-heading my-4 mt-3 text-white"> Welcome to my awesome Blog </h3>
                        <p class="text-light">We Love Django As much as you do..! &nbsp
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <div class="container">
        <div class="row">

            <!-- Blog Entries Column -->
            <div class="col-md-8 mt-3 left">
                {% for post in post_list %}
                    <!-- Blog Post -->
                    <div class="card mb-4">
                        <div class="card-body">
                            <h2 class="card-title">{{ post.title }}</h2>
                            <p class="card-text text-muted h6">
                                {{ post.author }} | {{ post.created_on }} | {{ post.comments.count }} comments
                            </p>

                            <p class="card-text">{{ post.content|safe|striptags|slice:":200" }}</p>
                            <a href="{% url 'post_detail' post.slug %}" class="btn btn-primary">Read More &rarr;</a>
                        </div>

                    </div>

                {% empty %}
                    <h1>OOps..! Noting Found</h1>
                {% endfor %}

            </div>

            {% block sidebar %}
                {% include 'sidebar.html' %}
            {% endblock sidebar %}
         {% include 'pagination.html' with page=posts %}
    </div>
    </div>
{% endblock %}

templates/post_by_category.html
{% extends "base.html" %} {% load humanize %}

{% block content %}

    <header class="masthead">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class=" col-md-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h3 class=" site-heading my-4 mt-3 text-white"> Welcome to my awesome Blog </h3>
                        <p class="text-light">We Love Django As much as you do..! &nbsp
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <div class="container">
        <div class="row">

            <!-- Blog Entries Column -->
            <div class="col-md-8 mt-3 left">
                {% for post in posts %}
                    <!-- Blog Post -->
                    <div class="card mb-4">
                        <div class="card-body">
                            <h2 class="card-title">{{ post.title }}</h2>
                            <a class="card-text text-muted h6">
                                by <a href="#">{{ post.author }}</a> |
                                {{ post.created_on|naturaltime }} |
                                <a href="{% url 'post_detail' post.slug %}">{{ post.comments.count }}
                                    comments</a>
                            </p>

                            <p class="card-text">{{ post.content|safe|striptags|slice:":200" }}</p>
                            <a href="{% url 'post_detail' post.slug %}" class="btn btn-primary">Read More &rarr;</a>
                            <br/>
                            Category: <a href="#">{{ post.category }}</a>
                            <br/>
                            Tags:
                            {% for tag in post.tags.all %}
                                <a href="#">{{ tag.name }}</a>
                            {% empty %}
                                none
                            {% endfor %}
                        </div>

                    </div>

                {% empty %}
                    <h1>OOps..! Noting Found</h1>
                {% endfor %}

            </div>

            {% block sidebar %}
                {% include 'sidebar.html' %}
            {% endblock sidebar %}
            {% include 'pagination.html' with page=posts %}
        </div>
    </div>
{% endblock %}

templates/post_by_tag.html
{% extends "base.html" %} {% load humanize %}

{% block content %}

    <header class="masthead">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class=" col-md-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h3 class=" site-heading my-4 mt-3 text-white"> Welcome to my awesome Blog </h3>
                        <p class="text-light">We Love Django As much as you do..! &nbsp
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <div class="container">
        <div class="row">

            <!-- Blog Entries Column -->
            <div class="col-md-8 mt-3 left">
                {% for post in posts %}
                    <!-- Blog Post -->
                    <div class="card mb-4">
                        <div class="card-body">
                            <h2 class="card-title">{{ post.title }}</h2>
                            <a class="card-text text-muted h6">
                                by <a href="#">{{ post.author }}</a> |
                                {{ post.created_on|naturaltime }} |
                                <a href="{% url 'post_detail' post.slug %}">{{ post.comments.count }}
                                    comments</a>
                            </p>

                            <p class="card-text">{{ post.content|safe|striptags|slice:":200" }}</p>
                            <a href="{% url 'post_detail' post.slug %}" class="btn btn-primary">Read More &rarr;</a>
                            <br/>
                            Category: <a href="#">{{ post.category }}</a>
                            <br/>
                            Tags:
                            {% for tag in post.tags.all %}
                                <a href="#">{{ tag.name }}</a>
                            {% empty %}
                                none
                            {% endfor %}
                        </div>

                    </div>

                {% empty %}
                    <h1>OOps..! Noting Found</h1>
                {% endfor %}

            </div>

            {% block sidebar %}
                {% include 'sidebar.html' %}
            {% endblock sidebar %}
            {% include 'pagination.html' with page=posts %}
        </div>
    </div>
{% endblock %}

templates/shop.html
{% load static %}
<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="pragma" content="no-cache"/>
    <meta http-equiv="cache-control" content="max-age=604800"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>GreatKart | One of the Biggest Online Shopping Platform</title>

    <link href="{% static 'images/favicon.ico' %}" rel="shortcut icon" type="image/x-icon">

    <!-- jQuery -->
    <script src="{% static 'js/jquery-2.0.0.min.js' %}" type="text/javascript"></script>

    <!-- Bootstrap4 files-->
    <script src="{% static 'js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css"/>

    <!-- Font awesome 5 -->
    <link href="{% static 'fonts/fontawesome/css/all.min.css' %}" type="text/css" rel="stylesheet">

    <!-- custom style -->
    <link href="{% static 'css/ui.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet" media="only screen and (max-width: 1200px)"/>

    <!-- custom javascript -->
    <script src="{% static 'js/script.js' %}" type="text/javascript"></script>

    <script type="text/javascript">
        /// some script

        // jquery ready start
        $(document).ready(function () {
            // jQuery code

        });
        // jquery end
    </script>

</head>
<body>
<header class="section-header">
    <nav class="navbar p-md-0 navbar-expand-sm navbar-light border-bottom">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTop4"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTop4">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link"> English </a>

                    </li>
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link"> USD </a>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    <li><a href="#" class="nav-link"> <i class="fa fa-envelope"></i> Email </a></li>
                    <li><a href="#" class="nav-link"> <i class="fa fa-phone"></i> Call us </a></li>
                </ul> <!-- list-inline //  -->
            </div> <!-- navbar-collapse .// -->
        </div> <!-- container //  -->
    </nav>

    <section class="header-main border-bottom">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-2 col-md-3 col-6">
                    <a href="{% url 'shop:home' %}" class="brand-wrap">
                        <img class="logo" src="{% static 'images/logo.png' %}">
                    </a> <!-- brand-wrap.// -->
                </div>
                <div class="col-lg col-sm col-md col-6 flex-grow-0">
                    <div class="category-wrap dropdown d-inline-block float-right">
                        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-bars"></i> All category
                        </button>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'shop:home' %}">All Products</a>
                            {% for category in links %}
                                <a class="dropdown-item" href="{{ category.get_url }}">{{ category.category_name }}</a>
                            {% endfor %}
                        </div>
                    </div>  <!-- category-wrap.// -->
                </div> <!-- col.// -->
                <a href="{% url 'shop:store' %}" class="btn btn-outline-primary">Store</a>
                <div class="col-lg  col-md-6 col-sm-12 col">
                    <form action="#" class="search">
                        <div class="input-group w-100">
                            <input type="text" class="form-control" style="width:60%;" placeholder="Search">

                            <div class="input-group-append">
                                <button class="btn btn-primary" type="submit">
                                    <i class="fa fa-search"></i>
                                </button>
                            </div>
                        </div>
                    </form> <!-- search-wrap .end// -->
                </div> <!-- col.// -->
                <div class="col-lg-3 col-sm-6 col-8 order-2 order-lg-3">
                    <div class="d-flex justify-content-end mb-3 mb-lg-0">
                        <div class="widget-header">
                            <small class="title text-muted">Welcome guest!</small>
                            <div>
                                <a href="./signin.html">Sign in</a> <span class="dark-transp"> | </span>
                                <a href="./register.html"> Register</a>
                            </div>
                        </div>
                        <a href="./cart.html" class="widget-header pl-3 ml-3">
                            <div class="icon icon-sm rounded-circle border">
                                <i class="fa fa-shopping-cart"></i>
                            </div>
                            <span class="badge badge-pill badge-danger notify">0</span>
                        </a>
                    </div> <!-- widgets-wrap.// -->
                </div> <!-- col.// -->
            </div> <!-- row.// -->
        </div> <!-- container.// -->
    </section> <!-- header-main .// -->


</header> <!-- section-header.// -->


{% block content %}

{% endblock %}

<!-- ========================= FOOTER ========================= -->
<footer class="section-footer border-top">
    <div class="container">
        <section class="footer-bottom border-top row">
            <div class="col-md-2">
                <p class="text-muted"> &copy 2019 Company name </p>
            </div>
            <div class="col-md-8 text-md-center">
                <span class="px-2">info@pixsellz.io</span>
                <span class="px-2">+879-332-9375</span>
                <span class="px-2">Street name 123, Avanue abc</span>
            </div>
            <div class="col-md-2 text-md-right text-muted">
                <i class="fab fa-lg fa-cc-visa"></i>
                <i class="fab fa-lg fa-cc-paypal"></i>
                <i class="fab fa-lg fa-cc-mastercard"></i>
            </div>
        </section>
    </div><!-- //container -->
</footer>
<!-- ========================= FOOTER END // ========================= -->

</body>
</html>